### ISSUE TITLE
Default expires_in override global_cache_options

### ISSUE THREAD

**Issue by hemslo** [artsy/garner#91]
In README
* `:global_cache_options`: A hash of options to be passed on every call to `Garner.config.cache`, like `{ :expires_in => 10.minutes }`. Defaults to `{}`

But In https://github.com/artsy/garner/blob/bbe95a45ca03a7a5ee7b172c3450ef95d1c10d95/lib%2Fgarner%2Fcache%2Fidentity.rb#L15
```ruby
@options_hash = Garner.config.global_cache_options || {}
@options_hash.merge!(expires_in: Garner.config.expires_in)
```
The default `expires_in` is `nil`, it will override `expires_in` in `global_cache_options`.
So possible changes:
* Update README to use another key name and add `expires_in` to full list of `Garner.config` attributes.

Or
```ruby
@options_hash[:expires_in] ||= Garner.config.expires_in
```

**Comment by fancyremarker** [comment]
@hemslo: This seems like a bug to me. I've implemented the second possible change you described above in #92.
